### ISSUE TITLE
Failed to activate the dayone package

### ISSUE THREAD

**Issue by qingfeng** [hem6/atom-dayone#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.3
**Thrown From**: [dayone](https://github.com/hem6/atom-dayone) package, v0.2.0
### Stack Trace

Failed to activate the dayone package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/qingfeng/Dropbox/atom_config/packages/dayone/lib/dayone-view.coffee:1:1)
  at /Users/qingfeng/Dropbox/atom_config/packages/dayone/lib/dayone-view.coffee:5:3
  at Object.<anonymous> (/Users/qingfeng/Dropbox/atom_config/packages/dayone/lib/dayone-view.coffee:79:5)
  at Object.<anonymous> (/Users/qingfeng/Dropbox/atom_config/packages/dayone/lib/dayone-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/qingfeng/Dropbox/atom_config/packages/dayone/lib/dayone.coffee:1:14)
  at Object.<anonymous> (/Users/qingfeng/Dropbox/atom_config/packages/dayone/lib/dayone.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:759:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:261:14)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:239:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:836:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:222:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -0:05.8.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:02.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:02.0 dayone:create (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "pep8",
      "task-list"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
bottom-dock, v0.2.2
color-picker, v2.0.11
counter, v0.3.3
dayone, v0.2.0
django-templates, v0.5.0
editor-stats, v0.17.0
editorconfig, v1.0.1
file-icons, v1.6.3
language-asciidoc, v0.11.1
language-django, v0.1.1
language-erlang, v3.0.0
language-slim, v0.5.0
linter, v1.3.4
linter-flake8, v1.6.1
linter-jscs, v2.0.4
local-history, v3.2.3
monokai, v0.18.0
pigments, v0.10.0
react, v0.12.6
todo-manager, v0.1.6
travis-ci-status, v0.16.0
zentabs, v0.8.6

# Dev
No dev packages
```

**Comment by hem6** [comment]
Fixed in ef8dbeb.
Thank you for reporting.
